// ---------------------------------------------------------------------------
// RUN
// ---------------------------------------------------------------------------

import type { Repo } from "../../repo.ts";
import { esc, openGates, scoreNodes, captionTime, type ScoreNode, type NodeState } from "../../derive.ts";
import { loadExtras } from "../../extra.ts";
import { buildTimeline, type TimelineActor } from "../../timeline.ts";
import type { DaemonInvocation } from "../../daemon.ts";
import { resolveOrchestratorStatus, type OrchestratorStatus } from "../../orchestrator-status.ts";
import { snodeClass, fromNodeState } from "../status.ts";
import { statusBadge, orchTurn, emptyState } from "../components.ts";
import {
  shell,
  pageBody,
  railNav,
  gateCardHtml,
  dispatchingFor,
  orchestratorPanel,
  memberAvatar,
  artifactFileName,
  artifactTokenLink,
  typeGlyphSvg,
} from "./shell.ts";

// The run-view score rail's node marker class — a thin, verbatim-preserving wrapper over
// status.ts's canonical `fromNodeState`/`snodeClass` (NOTES UI1: this used to be the ONE place that
// got the palette right; it's now generated by the same shared map every other status marker in the
// product uses, rather than being its own bespoke correct implementation). Exported and pure so a
// test can assert, for every reachable state, that the class emitted here has a matching rule in
// assets/styles.css — a mismatched class renders a real DOM node with zero visible size, not a
// missing one.
export function scoreNodeClass(n: Pick<ScoreNode, "state">, isGate: boolean): string {
  return `snode ${snodeClass(fromNodeState(n.state, isGate))}`;
}

// Phase 2 cluster 3, part 2/4 (the approved score-rail swing): the connecting line now reads as
// literal run progress — a settled thread behind a done node, a state-tinted frontier at wherever the
// run currently sits (active or an open gate), a plain dashed rest ahead. Keyed on the CURRENT node's
// own state (the segment below it), exactly the rule the approved dev/foundation/score.html showcase
// demonstrated — exported so a test can assert every reachable class has a matching styles.css rule,
// the same discipline scoreNodeClass above already gets.
export function scoreLineClass(state: NodeState): string {
  if (state === "done") return "sstep__line--past";
  if (state === "active") return "sstep__line--frontier";
  if (state === "gate") return "sstep__line--frontier-gate";
  return "sstep__line--future";
}

// "1m 42s" / "1h 04m" — elapsed since a live invocation's real `startedAt` (never a fabricated
// number; see ScoreNode.live's own doc comment on why the live strip has no token count).
export function elapsedLabel(startedAtIso: string, now: Date): string {
  const totalS = Math.max(0, Math.floor((now.getTime() - new Date(startedAtIso).getTime()) / 1000));
  const h = Math.floor(totalS / 3600);
  const m = Math.floor((totalS % 3600) / 60);
  const s = totalS % 60;
  if (h > 0) return `${h}h ${String(m).padStart(2, "0")}m`;
  return `${m}m ${String(s).padStart(2, "0")}s`;
}

// Phase 2 cluster 3 part 3: "actor avatars — agent initials on team tint, the Conductor as the only
// solid-filled disc, the Runner deliberately gray" (base brief, Run view). A ledger row's `actor.name`
// for a "member" is already `team/member` (ledger.ndjson's own shape, the same convention
// `artifact.produced_by` uses) — `memberAvatar` takes that directly, no extra lookup. Conductor/Runner
// identities are resolved in timeline.ts from the exact git identities every real commit funnels
// through (git.ts#CONDUCTOR_NAME/RUNNER_NAME) — never guessed here. "unknown" (a git author that is
// neither) deliberately renders no avatar at all, same as before this feature existed: inventing a
// fourth avatar treatment for an actor the design brief never named would be a fabricated channel, not
// a faithful rendering of the vocabulary it does define.
function timelineActorAvatar(repo: Repo, actor: TimelineActor): string {
  if (actor.kind === "conductor") return `<span class="avatar avatar--conductor sm" title="you">C</span>`;
  if (actor.kind === "runner") return `<span class="avatar avatar--runner sm" title="runner">R</span>`;
  if (actor.kind === "member") return memberAvatar(repo, actor.name);
  return "";
}

export function renderRun(repo: Repo, project: string, unitId: string, root: string, now: Date = new Date(), running: DaemonInvocation[] = [], status: OrchestratorStatus = resolveOrchestratorStatus()): string {
  const unit = repo.units.find((u) => u.project === project && u.unit === unitId);
  if (!unit) throw new Error(`unknown unit '${project}/${unitId}'`);
  const type = repo.types.get(unit.type);
  // `running` threads the daemon's live-invocation projection into scoreNodes (Phase 2 cluster 3 part
  // 4) — the score rail's "active" state was previously unreachable from real data (a step with no
  // artifact yet always read as plain "wait"); a step a member is genuinely producing right now shows
  // the canonical blue+pulse, with the real producer in the avatar column, instead of a false hollow.
  const nodes = scoreNodes(repo, unit, running);
  const gates = openGates(repo).filter((g) => g.project === project && g.unit === unitId);

  const scoreSteps = nodes
    .map((n) => {
      const isGate = n.shape === "diamond";
      // Row-level modifier classes: "done"/"upcoming"/"blocked" dim/style the whole step (fixes a
      // dormant rule — assets/styles.css's `.sstep.upcoming`/`.sstep.blocked` label-dimming was never
      // actually reachable before this: the prior computation only ever emitted "done" or ""). "is-live"/
      // "is-open" carry the approved rail's actionable-tint row wash (--active-panel/--gate-panel) —
      // the same "tint only when actionable" vocabulary the stat band and gate cards already use.
      const rowStateCls = n.state === "done" ? "done" : n.state === "wait" ? "upcoming" : n.state === "blocked" ? "blocked" : "";
      const rowLiveCls = n.state === "active" ? "is-live" : n.state === "gate" ? "is-open" : "";
      const rowCls = ["sstep", rowStateCls, rowLiveCls].filter(Boolean).join(" ");
      const snodeCls = scoreNodeClass(n, isGate);
      const av = n.producedBy ? `<div class="sstep__av">${memberAvatar(repo, n.producedBy)}</div>` : `<div class="sstep__av"></div>`;
      // NOTES UI1: "blocked" used to render with the SAME red inline style as "rejected" — a direct
      // violation of the design brief's canonical palette ("blocked = hollow neutral ... never
      // orange [or red]; failed = red" are two different states). Routed through the canonical map:
      // rejected is genuinely `failed` (red stays); blocked is genuinely `blocked` (hollow neutral).
      const chip =
        n.state === "done" ? statusBadge("done", "approved", "sstep__chip")
        : n.state === "gate" ? statusBadge("needs-you", "needs you", "sstep__chip")
        : n.state === "rejected" ? statusBadge("failed", "rejected", "sstep__chip")
        // NOTES F3: a blocked-status artifact (a member ran and failed) previously showed only a small
        // colored dot with no label — the reason itself (now including the member's stderr) is a click
        // away via the artifact link already rendered in `sub`, but nothing told the Conductor to click.
        : n.state === "blocked" ? statusBadge("blocked", "blocked", "sstep__chip")
        : "";
      const sub = n.artifact
        ? `${esc(n.artifact.produced_by)} &middot; ${artifactTokenLink(n.artifact.project, n.artifact.unit, n.artifact.id, artifactFileName(n.artifact))}`
        : n.state === "active" && n.producedBy
          ? `${esc(n.producedBy)} &middot; producing&hellip;`
          : "queued";
      // Tier 3 (amendment 1 §2 R4, 10s+): the live strip — round n/m (only when this kind belongs to
      // a review loop; a plain one-shot step has no round to state), plus real elapsed time. No token
      // count (see ScoreNode.live's doc comment) — the strip states only what's actually known.
      const liveStrip =
        n.state === "active" && n.live
          ? `<div class="sstep__live"><span class="ld" aria-hidden="true"></span><span>${
              n.live.loop ? `<b>${n.live.loop.round}</b>/${n.live.loop.maxRounds} &middot; ` : ""
            }${elapsedLabel(n.live.startedAt, now)}</span></div>`
          : "";
      const lineHtml = `<span class="sstep__line ${scoreLineClass(n.state)}" aria-hidden="true"></span>`;
      return `<div class="${rowCls}">
        <div class="sstep__head">
          <div class="sstep__rail"><span class="${snodeCls}" aria-hidden="true"></span>${lineHtml}</div>
          ${av}
          <span class="sstep__label">${esc(n.kind)}</span>
        </div>
        <div class="sstep__meta"><span class="sstep__sub">${sub}</span>${chip}${liveStrip}</div>
      </div>`;
    })
    .join("\n");

  const rail = railNav(repo, loadExtras(root));

  const timeline = buildTimeline(root, unit.dir);
  const timelineHtml = timeline.length
    ? timeline
        .map(
          (t) =>
            `<div class="tlrow"><span class="tlrow__time mono">${esc(t.ts.slice(0, 16).replace("T", " "))}</span><span class="tlrow__text">${timelineActorAvatar(repo, t.actor)}${t.text}</span></div>`,
        )
        .join("\n")
    : emptyState({ message: "No recorded events yet." });

  // Gate-review round 2, item 1: the score is this page's primary content, not navigation — it now
  // renders as its own content column beside the timeline (a plain inline flex row; no new CSS class,
  // the same inline-layout-override pattern the stat strips already use for their grid-template).
  const scoreCol = `<div style="flex:1 1 260px;min-width:220px">
    <div class="sec__h"><h2>Score</h2></div>
    <div class="score2" style="margin-top:14px">${scoreSteps}</div>
  </div>`;
  const timelineCol = `<div style="flex:2 1 360px;min-width:280px">
    <div class="sec__h"><h2>Timeline <span class="mono" style="color:var(--fg-mute);font-weight:400">&middot; from git log + runner events</span></h2></div>
    <div class="timeline">${timelineHtml}</div>
  </div>`;

  const main = `<main class="main">
    <header class="phead">
      <div class="crumb"><a href="/studio">studio</a><span>/</span><a href="/project/${esc(project)}">${esc(project)}</a><span>/</span><span>${esc(unitId)}</span></div>
      <h1><span style="display:inline-flex;vertical-align:-3px;margin-right:9px;color:var(--fg-mute)" aria-hidden="true">${typeGlyphSvg(type?.name, 20)}</span>${esc(unitId)}</h1>
    </header>
    <section class="sec">
      <div style="display:flex;gap:32px;align-items:flex-start;flex-wrap:wrap">${scoreCol}${timelineCol}</div>
    </section>
  </main>`;

  const gateHtml = gates.map((g) => gateCardHtml(repo, g, now, { cta: true, dispatching: dispatchingFor(running, g) })).join("\n");
  const briefingBody = orchTurn(
    `<p class="turn__body">${gates.length ? `${esc(gates[0].label)} is ready for review below.` : "No open gate on this unit right now."}</p>`,
    { captionTime: captionTime(now.toISOString(), now), captionLabel: "briefing" },
  );
  const orch = orchestratorPanel(project, status, briefingBody, gateHtml, root, now);

  return shell(`levare · run · ${unitId}`, "Open score", pageBody(rail, main, orch), status);
}
