// ---------------------------------------------------------------------------
// RUN
// ---------------------------------------------------------------------------

import type { Repo } from "../../repo.ts";
import { esc, openGates, scoreNodes, captionTime, gateBriefingSentence, elapsedLabel, elapsedSpan, type ScoreNode, type NodeState } from "../../derive.ts";
import { loadExtras } from "../../extra.ts";
import { buildTimeline, type TimelineActor } from "../../timeline.ts";
import type { DaemonInvocation } from "../../daemon.ts";
import { resolveOrchestratorStatus, type OrchestratorStatus } from "../../orchestrator-status.ts";
import { snodeClass, fromNodeState } from "../status.ts";
import { statusBadge, neutralChip, orchTurn, emptyState, callout } from "../components.ts";
import {
  shell,
  pageBody,
  railNav,
  gateCardHtml,
  dispatchingFor,
  orchestratorPanel,
  memberAvatar,
  artifactFileName,
  artifactTokenLink,
  typeGlyphSvg,
} from "./shell.ts";

// The run-view score rail's node marker class — a thin, verbatim-preserving wrapper over
// status.ts's canonical `fromNodeState`/`snodeClass` (NOTES UI1: this used to be the ONE place that
// got the palette right; it's now generated by the same shared map every other status marker in the
// product uses, rather than being its own bespoke correct implementation). Exported and pure so a
// test can assert, for every reachable state, that the class emitted here has a matching rule in
// assets/styles.css — a mismatched class renders a real DOM node with zero visible size, not a
// missing one.
export function scoreNodeClass(n: Pick<ScoreNode, "state">, isGate: boolean): string {
  return `snode ${snodeClass(fromNodeState(n.state, isGate))}`;
}

// Phase 2 cluster 3, part 2/4 (the approved score-rail swing): the connecting line now reads as
// literal run progress — a settled thread behind a done node, a state-tinted frontier at wherever the
// run currently sits (active or an open gate), a plain dashed rest ahead. Keyed on the CURRENT node's
// own state (the segment below it), exactly the rule the approved dev/foundation/score.html showcase
// demonstrated — exported so a test can assert every reachable class has a matching styles.css rule,
// the same discipline scoreNodeClass above already gets.
export function scoreLineClass(state: NodeState): string {
  if (state === "done") return "sstep__line--past";
  if (state === "active") return "sstep__line--frontier";
  if (state === "gate") return "sstep__line--frontier-gate";
  return "sstep__line--future";
}

// Re-exported so existing callers (board/render.ts's barrel, tests) keep importing it from here — the
// implementation moved to derive.ts (Phase 2 "gate card" goal, item 2) so shell.ts's gate card can use
// the exact same helper without a run.ts↔shell.ts import cycle. See ScoreNode.live's own doc comment
// for why the live strip built on it has no token count.
export { elapsedLabel };

// Phase 2 cluster 3 part 3: "actor avatars — agent initials on team tint, the Conductor as the only
// solid-filled disc, the Runner deliberately gray" (base brief, Run view). A ledger row's `actor.name`
// for a "member" is already `team/member` (ledger.ndjson's own shape, the same convention
// `artifact.produced_by` uses) — `memberAvatar` takes that directly, no extra lookup. Conductor/Runner/
// member identities are resolved in timeline.ts's `resolveGitActor`, exhaustive over every identity
// shape the app itself produces — never guessed here. "unknown" (a git identity matching none of those)
// deliberately renders no avatar at all, same as before this feature existed: inventing a fourth avatar
// treatment for an actor the design brief never named would be a fabricated channel, not a faithful
// rendering of the vocabulary it does define.
function timelineActorAvatar(repo: Repo, actor: TimelineActor): string {
  // Finding 90: the SAME solid "C" disc for both — a studio-declared Conductor identity means "this is
  // the same human", not "this is a different, lesser kind of Conductor action" — but the tooltip keeps
  // the one distinction that must survive unification: whether levare's own commitAs made this exact
  // commit, or the Conductor made it directly with their own git identity outside the app. See
  // timeline.ts#TimelineActor's own doc on why collapsing that into one indistinguishable label would
  // misrepresent git log as a record of human decisions.
  if (actor.kind === "conductor") return `<span class="avatar avatar--conductor sm" title="${actor.stamped === false ? "you — direct git commit" : "you — via levare"}">C</span>`;
  if (actor.kind === "runner") return `<span class="avatar avatar--runner sm" title="runner">R</span>`;
  if (actor.kind === "member") return memberAvatar(repo, actor.name);
  return "";
}

// Finding 90 (live-verification fix): the shared "C" avatar above unifies the PERSON, but a hover-only
// tooltip made a direct git commit and a levare-recorded approval look identical on a page glance —
// worse than the pre-fix "unknown" row, which was at least visibly blank. This tag is the visible half
// of that distinction, exported (same convention as scoreNodeClass/scoreLineClass above) so a test can
// exercise it without a full render fixture. Neutral wording on purpose ("direct", not
// "unverified"/"manual") — a Conductor hand-editing the registry is ordinary, not irregular; the tag
// states how the commit happened, it doesn't grade it. Only the exceptional case (`stamped: false`)
// gets it — the ordinary app-mediated commit stays unmarked.
export function timelineDirectTag(actor: TimelineActor): string {
  return actor.kind === "conductor" && actor.stamped === false ? ` <span class="tag" title="committed directly with the Conductor's own git identity, not through levare">direct</span>` : "";
}

export function renderRun(repo: Repo, project: string, unitId: string, root: string, now: Date = new Date(), running: DaemonInvocation[] = [], status: OrchestratorStatus = resolveOrchestratorStatus()): string {
  const unit = repo.units.find((u) => u.project === project && u.unit === unitId);
  if (!unit) throw new Error(`unknown unit '${project}/${unitId}'`);
  const type = repo.types.get(unit.type);
  // `running` threads the daemon's live-invocation projection into scoreNodes (Phase 2 cluster 3 part
  // 4) — the score rail's "active" state was previously unreachable from real data (a step with no
  // artifact yet always read as plain "wait"); a step a member is genuinely producing right now shows
  // the canonical blue+pulse, with the real producer in the avatar column, instead of a false hollow.
  const nodes = scoreNodes(repo, unit, running);
  const gates = openGates(repo).filter((g) => g.project === project && g.unit === unitId);

  const scoreSteps = nodes
    .map((n, nodeIndex) => {
      const isGate = n.shape === "diamond";
      // Row-level modifier classes: "done"/"upcoming"/"blocked" dim/style the whole step (fixes a
      // dormant rule — assets/styles.css's `.sstep.upcoming`/`.sstep.blocked` label-dimming was never
      // actually reachable before this: the prior computation only ever emitted "done" or ""). "is-live"/
      // "is-open" carry the approved rail's actionable-tint row wash (--active-panel/--gate-panel) —
      // the same "tint only when actionable" vocabulary the stat band and gate cards already use.
      const rowStateCls = n.state === "done" ? "done" : n.state === "wait" ? "upcoming" : n.state === "blocked" || n.state === "unreachable" ? "blocked" : "";
      const rowLiveCls = n.state === "active" ? "is-live" : n.state === "gate" ? "is-open" : "";
      const rowCls = ["sstep", rowStateCls, rowLiveCls].filter(Boolean).join(" ");
      const snodeCls = scoreNodeClass(n, isGate);
      // DOCS-WALKTHROUGH-3 item 3: the score rail's own avatar names its member on hover/focus, not
      // just by two letters — `nodeIndex` makes the tooltip id unique even when the same member
      // produces more than one node in this unit's flow.
      const av = n.producedBy
        ? `<div class="sstep__av">${memberAvatar(repo, n.producedBy, { tooltipId: `scorerail-${esc(project)}-${esc(unitId)}-${nodeIndex}` })}</div>`
        : `<div class="sstep__av"></div>`;
      // NOTES UI1: "blocked" used to render with the SAME red inline style as "rejected" — a direct
      // violation of the design brief's canonical palette ("blocked = solid neutral gray ... never
      // orange [or red]; failed = red" are two different states). Routed through the canonical map:
      // rejected is genuinely `failed` (red stays); blocked is genuinely `blocked` (neutral gray).
      const chip =
        n.state === "done" ? statusBadge("done", "approved", "sstep__chip")
        // Finding 59: a "gate" node whose in-review artifact is a loop's companion kind (F16 — the
        // round's real, decision-bearing gate is the OTHER side, the one the loop's `until` names)
        // is not a second thing the Conductor must act on. It's still genuinely in-review and still
        // part of one open round (diamond shape, ruling C2, is unchanged) — just neutral like "not
        // covered" below, not brass: this turn already did its job, nothing here is broken or waiting
        // on this Conductor specifically.
        : n.state === "gate" && n.loopCompanion
          ? neutralChip("under review", "sstep__chip", {
              text: "this round's decision is on the other artifact, not this one",
              id: `loopcompanion-${esc(project)}-${esc(unitId)}-${esc(n.kind)}`,
            })
        : n.state === "gate" ? statusBadge("needs-you", "needs you", "sstep__chip")
        : n.state === "rejected" ? statusBadge("failed", "rejected", "sstep__chip")
        // NOTES F3: a blocked-status artifact (a member ran and failed) previously showed only a small
        // colored dot with no label — the reason itself (now including the member's stderr) is a click
        // away via the artifact link already rendered in `sub`, but nothing told the Conductor to click.
        : n.state === "blocked" ? statusBadge("blocked", "blocked", "sstep__chip")
        // NOTES "not covered" (Conductor ruling): its own chip, distinct from "blocked" — a blocked
        // artifact is a Conductor decision away from moving; this stage never is (no member of the
        // team ever produces it), and stacking several down a rail must read as present-but-inactive
        // information about the type's shape, not as a run of failures. Neutral (never a lifecycle
        // colour, including "blocked"'s own) — see neutralChip's own doc.
        //
        // NOTES "not covered tooltip": the fuller sentence used to live as a permanently-visible
        // sub-line, repeating on every uncovered row and wrapping to two lines on a wide type — pure
        // explanation, not a decision a Conductor makes per row. A reader asks "why is this row greyed
        // out" once; that's what a tooltip is for (deliberately asymmetric with the loop bounds
        // tooltip below, which STAYS visible unconditionally — see that tooltip's own doc for why).
        : n.state === "unreachable"
          ? neutralChip("not covered", "sstep__chip", {
              text: "no member of this team produces this",
              id: `notcovered-${esc(project)}-${esc(unitId)}-${esc(n.kind)}`,
            })
        : "";
      const sub = n.artifact
        ? `${esc(n.artifact.produced_by)} &middot; ${artifactTokenLink(n.artifact.project, n.artifact.unit, n.artifact.id, artifactFileName(n.artifact))}`
        : n.state === "active" && n.producedBy
          ? `${esc(n.producedBy)} &middot; producing&hellip;`
          // NOTES "not covered tooltip": no sub-line at all here now — the chip alone (with its
          // on-demand tooltip, above) already says "not covered"; repeating it in prose underneath
          // would be the exact redundant-explanation the tooltip move exists to remove.
          : n.state === "unreachable"
            ? ""
            : "queued";
      // Tier 3 (amendment 1 §2 R4, 10s+): the live strip — round n/m (only when this kind belongs to
      // a review loop; a plain one-shot step has no round to state), plus real elapsed time. No token
      // count (see ScoreNode.live's doc comment) — the strip states only what's actually known.
      //
      // Goal "registry cards legibility" item 2 ruling: the registry card's own loop enclosure moved
      // `until`/`on_exhaust` to a hover/focus affordance, since the enclosure can't carry that text
      // inline without pulling the loop off its sequence — but that affordance doesn't reach touch,
      // screenshots, or a registry audit. The condition attached to that move: the SAME two facts
      // render here UNCONDITIONALLY, right where the round count is already live, never behind an
      // interaction — this is where a Conductor watching a loop actually needs them.
      const liveStrip =
        n.state === "active" && n.live
          ? `<div class="sstep__live"><span class="ld" aria-hidden="true"></span><span>${
              n.live.loop ? `<b>${n.live.loop.round}</b>/${n.live.loop.maxRounds} &middot; ` : ""
            }${elapsedSpan(n.live.startedAt, now, n.live.timeoutS)}${
              n.live.loop ? ` &middot; until ${esc(n.live.loop.until)} &middot; on_exhaust: ${esc(n.live.loop.onExhaust)}` : ""
            }</span></div>`
          : "";
      const lineHtml = `<span class="sstep__line ${scoreLineClass(n.state)}" aria-hidden="true"></span>`;
      // The rail is now a sibling of `.sstep__body` (head + meta stacked), not nested inside the head
      // — it stretches to the row's REAL height (flex's own default align-items:stretch, driven by
      // body's natural content height) instead of a fixed guess. The node stays pinned to a fixed
      // offset from the row's top (matching the head's own fixed height) via absolute positioning
      // inside the now-variable-height rail, so alignment is untouched; the LINE can now reach all
      // the way down through however tall this row's meta content actually is, plus the fixed gap to
      // the next row's node — see assets/styles.css's own comment on `.sstep__rail`/`.sstep__line` for
      // why a fixed bottom offset alone (the prior approach) undershot on anything but the shortest row.
      return `<div class="${rowCls}">
        <div class="sstep__rail"><span class="${snodeCls}" aria-hidden="true"></span>${lineHtml}</div>
        <div class="sstep__body">
          <div class="sstep__head">
            ${av}
            <span class="sstep__label">${esc(n.kind)}</span>
          </div>
          <div class="sstep__meta"><span class="sstep__sub">${sub}</span>${chip}${liveStrip}</div>
        </div>
      </div>`;
    })
    .join("\n");

  const rail = railNav(repo, loadExtras(root));

  const { rows: timeline, unavailable: timelineUnavailable } = buildTimeline(root, unit, repo.projects.get(project), repo.studio.conductorGitIdentity);
  const timelineHtml = timeline.length
    ? timeline
        .map((t) => {
          // Date and time render as two explicit, independently-nowrap lines — never one run of text
          // left to the browser's own line-breaking, which (at this column's width) was choosing to
          // break mid-token at the ISO date's own hyphens ("2026-" / "07-07" / "09:12"), not just at
          // the natural date/time boundary.
          const dateStr = t.ts.slice(0, 10);
          const timeStr = t.ts.slice(11, 16);
          return `<div class="tlrow"><span class="tlrow__time mono"><span class="tlrow__date">${esc(dateStr)}</span><span class="tlrow__clock">${esc(timeStr)}</span></span><span class="tlrow__text">${timelineActorAvatar(repo, t.actor)}${t.text}${timelineDirectTag(t.actor)}</span></div>`;
        })
        .join("\n")
    : emptyState({ message: "No recorded events yet." });

  // Gate-review round 2, item 1: the score is this page's primary content, not navigation — it now
  // renders as its own content column beside the timeline (a plain inline flex row; no new CSS class,
  // the same inline-layout-override pattern the stat strips already use for their grid-template).
  const scoreCol = `<div style="flex:1 1 260px;min-width:220px">
    <div class="sec__h"><h2>Score</h2></div>
    <div class="score2" style="margin-top:14px">${scoreSteps}</div>
  </div>`;
  const timelineNotice = timelineUnavailable ? callout("note", `timeline is incomplete &mdash; ${esc(timelineUnavailable)}`) : "";
  const timelineCol = `<div style="flex:2 1 360px;min-width:280px">
    <div class="sec__h"><h2>Timeline <span class="mono" style="color:var(--fg-mute);font-weight:400">&middot; from git log + runner events</span></h2></div>
    ${timelineNotice}
    <div class="timeline">${timelineHtml}</div>
  </div>`;

  const main = `<main class="main">
    <header class="phead">
      <div class="crumb"><a href="/studio">studio</a><span>/</span><a href="/project/${esc(project)}">${esc(project)}</a><span>/</span><span>${esc(unitId)}</span></div>
      <h1><span style="display:inline-flex;vertical-align:-3px;margin-right:9px;color:var(--fg-mute)" aria-hidden="true">${typeGlyphSvg(type?.name, 20)}</span>${esc(unitId)}</h1>
    </header>
    <section class="sec">
      <div style="display:flex;gap:32px;align-items:flex-start;flex-wrap:wrap">${scoreCol}${timelineCol}</div>
    </section>
  </main>`;

  const gateHtml = gates.map((g) => gateCardHtml(repo, g, now, { cta: true, dispatching: dispatchingFor(repo, running, g) })).join("\n");
  const briefingBody = orchTurn(
    `<p class="turn__body">${gates.length ? gateBriefingSentence(gates[0]) : "No open gate on this unit right now."}</p>`,
    { captionTime: captionTime(now.toISOString(), now), captionLabel: "briefing" },
  );
  const orch = orchestratorPanel(project, status, briefingBody, gateHtml, root, now);

  return shell(`levare · run · ${unitId}`, "Open score", pageBody(rail, main, orch), status);
}
