// ---------------------------------------------------------------------------
// RUN
// ---------------------------------------------------------------------------

import type { Repo } from "../../repo.ts";
import { esc, openGates, scoreNodes, captionTime, type ScoreNode } from "../../derive.ts";
import { loadExtras } from "../../extra.ts";
import { buildTimeline } from "../../timeline.ts";
import type { DaemonInvocation } from "../../daemon.ts";
import { resolveOrchestratorStatus, type OrchestratorStatus } from "../../orchestrator-status.ts";
import { snodeClass, fromNodeState } from "../status.ts";
import { statusBadge, orchTurn, emptyState } from "../components.ts";
import {
  shell,
  pageBody,
  railNav,
  gateCardHtml,
  dispatchingFor,
  orchestratorPanel,
  memberAvatar,
  artifactFileName,
  artifactTokenLink,
} from "./shell.ts";

// The run-view score rail's node marker class — a thin, verbatim-preserving wrapper over
// status.ts's canonical `fromNodeState`/`snodeClass` (NOTES UI1: this used to be the ONE place that
// got the palette right; it's now generated by the same shared map every other status marker in the
// product uses, rather than being its own bespoke correct implementation). Exported and pure so a
// test can assert, for every reachable state, that the class emitted here has a matching rule in
// assets/styles.css — a mismatched class renders a real DOM node with zero visible size, not a
// missing one.
export function scoreNodeClass(n: Pick<ScoreNode, "state">, isGate: boolean): string {
  return `snode ${snodeClass(fromNodeState(n.state, isGate))}`;
}

export function renderRun(repo: Repo, project: string, unitId: string, root: string, now: Date = new Date(), running: DaemonInvocation[] = [], status: OrchestratorStatus = resolveOrchestratorStatus()): string {
  const unit = repo.units.find((u) => u.project === project && u.unit === unitId);
  if (!unit) throw new Error(`unknown unit '${project}/${unitId}'`);
  const type = repo.types.get(unit.type);
  const nodes = scoreNodes(repo, unit);
  const gates = openGates(repo).filter((g) => g.project === project && g.unit === unitId);

  const scoreSteps = nodes
    .map((n) => {
      const isGate = n.shape === "diamond";
      const nodeCls = n.state === "done" ? "done" : isGate ? "" : "";
      const snodeCls = scoreNodeClass(n, isGate);
      const av = n.producedBy ? `<div class="sstep__av">${memberAvatar(repo, n.producedBy)}</div>` : `<div class="sstep__av"></div>`;
      // NOTES UI1: "blocked" used to render with the SAME red inline style as "rejected" — a direct
      // violation of the design brief's canonical palette ("blocked = hollow neutral ... never
      // orange [or red]; failed = red" are two different states). Routed through the canonical map:
      // rejected is genuinely `failed` (red stays); blocked is genuinely `blocked` (hollow neutral).
      const chip =
        n.state === "done" ? statusBadge("done", "approved", "sstep__chip")
        : n.state === "gate" ? statusBadge("needs-you", "needs you", "sstep__chip")
        : n.state === "rejected" ? statusBadge("failed", "rejected", "sstep__chip")
        // NOTES F3: a blocked-status artifact (a member ran and failed) previously showed only a small
        // colored dot with no label — the reason itself (now including the member's stderr) is a click
        // away via the artifact link already rendered in `sub`, but nothing told the Conductor to click.
        : n.state === "blocked" ? statusBadge("blocked", "blocked", "sstep__chip")
        : "";
      const sub = n.artifact
        ? `${esc(n.artifact.produced_by)} &middot; ${artifactTokenLink(n.artifact.project, n.artifact.unit, n.artifact.id, artifactFileName(n.artifact))}`
        : "queued";
      return `<div class="sstep ${nodeCls}">
        <div class="sstep__rail"><span class="${snodeCls}" aria-hidden="true"></span><span class="sstep__line" aria-hidden="true"></span></div>
        ${av}
        <div class="sstep__body"><span class="sstep__label">${esc(n.kind)}</span><span class="sstep__sub">${sub}</span>${chip}</div>
      </div>`;
    })
    .join("\n");

  const rail = railNav(repo, loadExtras(root));

  const timeline = buildTimeline(root, unit.dir);
  const timelineHtml = timeline.length
    ? timeline
        .map((t) => `<div class="tlrow"><span class="tlrow__time mono">${esc(t.ts.slice(0, 16).replace("T", " "))}</span><span class="tlrow__text">${t.text}</span></div>`)
        .join("\n")
    : emptyState({ message: "No recorded events yet." });

  // Gate-review round 2, item 1: the score is this page's primary content, not navigation — it now
  // renders as its own content column beside the timeline (a plain inline flex row; no new CSS class,
  // the same inline-layout-override pattern the stat strips already use for their grid-template).
  const scoreCol = `<div style="flex:1 1 260px;min-width:220px">
    <div class="sec__h"><h2>Score</h2></div>
    <div class="score2" style="margin-top:14px">${scoreSteps}</div>
  </div>`;
  const timelineCol = `<div style="flex:2 1 360px;min-width:280px">
    <div class="sec__h"><h2>Timeline <span class="mono" style="color:var(--fg-mute);font-weight:400">&middot; from git log + runner events</span></h2></div>
    <div class="timeline">${timelineHtml}</div>
  </div>`;

  const main = `<main class="main">
    <header class="phead">
      <div class="crumb"><a href="/studio">studio</a><span>/</span><a href="/project/${esc(project)}">${esc(project)}</a><span>/</span><span>${esc(unitId)}</span></div>
      <h1><span style="font-family:var(--mono);font-weight:400;margin-right:8px" aria-hidden="true">${type?.glyph ?? ""}</span>${esc(unitId)}</h1>
    </header>
    <section class="sec">
      <div style="display:flex;gap:32px;align-items:flex-start;flex-wrap:wrap">${scoreCol}${timelineCol}</div>
    </section>
  </main>`;

  const gateHtml = gates.map((g) => gateCardHtml(repo, g, now, { cta: true, dispatching: dispatchingFor(running, g) })).join("\n");
  const briefingBody = orchTurn(
    `<p class="turn__body">${gates.length ? `${esc(gates[0].label)} is ready for review below.` : "No open gate on this unit right now."}</p>`,
    { captionTime: captionTime(now.toISOString(), now), captionLabel: "briefing" },
  );
  const orch = orchestratorPanel(project, status, briefingBody, gateHtml, root, now);

  return shell(`levare · run · ${unitId}`, "Open score", pageBody(rail, main, orch), status);
}
